# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["v0", "ci"]
  pull_request:
    branches: ["v0", "ci"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: 16
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build-all

  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "\033[31;1;4mDump GitHub context\033[0m"
          echo -e "$GITHUB_CONTEXT\n"
        shell: bash
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Git config
        run: |
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.actor }}"
      - name: Apply version bump (patch)
        run: npm version patch
      - name: Git push version bump
        run: git push origin "${{ github.event.push.ref }}" --follow-tags --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
